Numpy is a python library , was created in 2005 by Travis Oliphant, Numpy is used for working with arrays. Numpy is short form of "Numerical Python". 50x faster than traditional python lists.

In [3]:
#import library : numpy
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


different ways to create numpy array

In [ ]:
#to create an ndarray, we can pass a list,tuple or other array like object

In [6]:
#create 2D array
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [7]:
#To see the dimension of the array
print(arr3.ndim)

2


In [11]:
# to create 3D array
arr4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,8,7]]])
print(arr4)
print(arr4.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 8 7]]]
3


In [13]:
#Numpy Array indexing
arr5=np.array([1,2,3,4,5])
print(arr5[2])

3


In [18]:
#print starting from 0 to n=3
print(arr5[0:3])
#Negative index
print(arr5[-1])
#slicing
print(arr5[-2:-1])

[1 2 3]
5
[4]


In [23]:
#get 3rd and 4th element and add them
import numpy as np
arr6=np.array([1,2,3,4])
print( arr6[2] + arr6[3])
#access the element of the 1st row  and 2nd column
arr7=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr7)
print('2nd elemnt of the 1st row: ', arr7[0,1])
#acess the element of the 2nd row and 5th column
arr8=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr8[1,4])

7
[[1 2 3 4 5]
 [6 7 8 9 0]]
2nd elemnt of the 1st row:  2
10


In [24]:
#Q1. code snippet
arr9=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr9)
print(arr9[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [31]:
#negative 3D
import numpy as np
arr10=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr10[1,-1])
arr11=np.array([10,20,30,40,50,60,75])
print(arr11[1:5])
# from index 4 till end
print(arr11[4:])
#till index 4
print(arr11[:4])
# Negative slicing
print(arr11[-3:-1])
#return every other element from the entire array
print(arr11[::2])

10
[20 30 40 50]
[50 60 75]
[10 20 30 40]
[50 60]
[10 30 50 75]


In [35]:
#from 2nd element , slice elements from 1st index to 4th index,2D
import numpy as np
ar=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ar[1,1:4])
print(ar[0:2,2])
print(ar[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


DATA TYPES IN NumPy
NumPy has some extra data types, and refer to data types with one charactor , like i for integers, u for unsigned integers etc.

In [40]:
#Create an array with defined data types
import numpy as np
arr=np.array([1,2,3,4],dtype='I')
print(arr)
print(arr.dtype)
a=np.array([1,2,3,4],dtype='S')
print(a.dtype)

[1 2 3 4]
uint32
|S1


In [42]:
#change data type float to integer by using "i" as a parameter
import numpy as np
ae=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


In [44]:

#numpy array copy v/s view
#The main difference b/w a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

In [48]:
#Make a copy , change the original array , and display both arrays:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(x)
print(arr)
#view
y=arr.view()
print(x)

[1 2 3 4 5]
[42  2  3  4  5]
[1 2 3 4 5]


In [49]:
#Array SHAPE
#The shape of an 2D array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [50]:
#array reshaping
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [52]:
#Flattering the arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


NumPy Array iterating

Iterating means going through elements one by one .
As we deal with multi dimensional arrays in numpy, we can do this using basic for loop of python.
if we iterate on a 1D array it will go through each element one by one