## Numpy Laborarory Practice questions

# 1. Array Creation & Properties

1. Create a NumPy array from [10, 20, 30, 40, 50]. Display its shape, size, and data type.

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(5,)
5
int64


2. Create a 3 × 4 array containing numbers from 1 to 12.

In [2]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3. Create an array of zeros, an array of ones, and an identity matrix.

In [3]:
import numpy as np
zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((3, 3))
identity_arr = np.eye(3)
print(zeros_arr)
print(ones_arr)
print(identity_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Generate all even numbers between 10 and 50 using np.arange().

In [8]:
import numpy as np
even=np.arange(10,51,2)
print(even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


5. Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().

In [9]:
import numpy as np
arr=np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 2. Array Arithmetic

6. Given two NumPy arrays, perform element-wise addition, subtraction, multiplication,
and division.

In [10]:
import numpy as np
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 5, 8])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[12 24 35 48]
[ 8 16 25 32]
[ 20  80 150 320]
[5. 5. 6. 5.]


7. Calculate the square and cube of every element in a NumPy array.

In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.square(arr))
print(np.power(arr, 3))

[ 1  4  9 16 25]
[  1   8  27  64 125]


8. Increase every element of an array by 15%.

In [12]:
import numpy as np
arr = np.array([100.0, 200.0, 300.0])
updated_arr = arr * 1.15
print(updated_arr)

[115. 230. 345.]


9. Given two arrays, find their element-wise maximum and minimum.

In [13]:
import numpy as np
import numpy as np
arr1 = np.array([3, 8, 2, 10])
arr2 = np.array([5, 4, 9, 1])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[ 5  8  9 10]
[3 4 2 1]


# 3. Indexing & Slicing

10. Create an array from 0 to 20 and extract the first five elements, last five elements,
elements from index 5 to 15, and every second element.

In [14]:
import numpy as np
arr = np.arange(21)
print(arr[:5])
print(arr[-5:])
print(arr[5:16])
print(arr[::2])

[0 1 2 3 4]
[16 17 18 19 20]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 0  2  4  6  8 10 12 14 16 18 20]


11. Replace the first five elements of an array with 100.

In [15]:
import numpy as np
arr = np.arange(10)
arr[:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9]


12. Create an array and demonstrate the difference between a slice/view and a copy.

In [16]:
import numpy as np
original = np.array([1, 2, 3, 4, 5])
view_arr = original[1:4]
view_arr[0] = 999
copy_arr = original[1:4].copy()
copy_arr[1] = 888
print(original)
print(copy_arr)

[  1 999   3   4   5]
[999 888   4]


13. Reverse a NumPy array using slicing.

In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


# 4. 2-D Array Indexing & Slicing

14. Create the matrix [[10,20,30],[40,50,60],[70,80,90]]. Extract the second row, third
column, and element 50.

In [18]:
import numpy as np

matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

print(matrix[1, :])
print(matrix[:, 2])
print(matrix[1, 1])

[40 50 60]
[30 60 90]
50


15. From the matrix above, extract the sub-matrix [[20,30],[50,60]].

In [20]:
import numpy as np
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
sub_matrix = matrix[0:2, 1:3]
print(sub_matrix)

[[20 30]
 [50 60]]


16. Create a 5 × 5 matrix containing 1–25 and extract the first row, last column, middle
element, and top-left 3 × 3 matrix.

In [21]:
import numpy as np
matrix_5x5 = np.arange(1, 26).reshape(5, 5)
print(matrix_5x5[0, :])
print(matrix_5x5[:, -1])
print(matrix_5x5[2, 2])
print(matrix_5x5[0:3, 0:3])

[1 2 3 4 5]
[ 5 10 15 20 25]
13
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


# 5. Reshaping & Transpose

17. Create an array containing 1–12 and reshape it into a 3 × 4 matrix.

In [22]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


18. Reshape a 1-D array into a 2 × 5 matrix.

In [23]:
import numpy as np
arr_1d = np.arange(10)
matrix_2x5 = arr_1d.reshape(2, 5)
print(matrix_2x5)

[[0 1 2 3 4]
 [5 6 7 8 9]]


19. Convert a 3 × 4 matrix into a 4 × 3 matrix using transpose.

In [24]:
import numpy as np
matrix_3x4 = np.arange(12).reshape(3, 4)
matrix_4x3 = matrix_3x4.T
print(matrix_4x3)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


20. Use transpose() and swapaxes() on a 3-D array.

In [25]:
import numpy as np
arr_3d = np.arange(24).reshape(2, 3, 4)
transposed = arr_3d.transpose(1, 0, 2)
swapped = arr_3d.swapaxes(0, 1)
print(transposed.shape)
print(swapped.shape)

(3, 2, 4)
(3, 2, 4)
